
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           :title
relative_permalinks: false

# Setup
#timezone:            your timezone # eg. Asia/Kathmandu
locale:              en_use # eg. en_us
name:				         site name
title:               site title
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/r-blog/'
baseurl_posts_img:   '/r-blog/assets/images/posts/'
baseurl_featured_img: '/r-blog/assets/images/hero/'
baseurl_featured_thumbnail: '/r-blog/assets/images/thumbnail/'
baseurl_javascripts: '/r-blog/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Ryan Drew
  url:            	 your site url
  facebook:          ryanelliotdrew
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username
  instagram:         ryanelliotdrew
  email:             ryanelliotdrew@gmail.com

webmaster:
  name:              Jeremy Thompson

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml", ".sass-cache"]
port:             	 9001

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
